auth-server:
  base-url: http://localhost:8080
  auth-url: ${auth-server.base-url}/auth/realms/cyberid/protocol/openid-connect/auth
  token-url: ${auth-server.base-url}/auth/realms/cyberid/protocol/openid-connect/token

server:
  port: 6742

springdoc:
  swagger-ui:
    oauth:
      client-id: PartnerHub
      use-pkce-with-authorization-code-grant: true

spring:
  application:
    name: GRPC-Client
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth-server.base-url}/auth/realms/cyberid
          jwk-set-uri: ${auth-server.base-url}/auth/realms/cyberid/protocol/openid-connect/certs
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: dd-MM-yyyy HH:mm:ss

grpc:
  client:
    GRPC-Server:
      address: localhost:8090
    GLOBAL:
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
